#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# configure.sh - interactively generate demo.properties.
# Press Enter at any prompt to accept the [default] shown in brackets.
# Defaults target the ps-portal North/South lab.
# -----------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=demo.properties

ask() {  # ask "Prompt" "default" -> echoes the answer
  local prompt="$1" def="${2:-}" ans
  if [ -n "$def" ]; then read -r -p "$prompt [$def]: " ans; echo "${ans:-$def}"
  else                  read -r -p "$prompt: " ans;        echo "$ans"; fi
}

echo "============================================================"
echo "  Circuit Breaker Demo - configuration"
echo "============================================================"

if [ -f "$OUT" ]; then
  bak="$OUT.bak.$(date +%s)"
  cp "$OUT" "$bak"
  echo "Existing $OUT backed up to $bak"
fi

COUNT=$(ask "How many databases (2 or 3)" "2")
if [ "$COUNT" != "2" ] && [ "$COUNT" != "3" ]; then
  echo "Only 2 or 3 are supported. Defaulting to 2."; COUNT=2
fi

# Sensible defaults per slot
def_names=("North" "South" "Central")
def_eps=("redis-12002.re-cluster1.ps-redislabs.org:12002" \
         "redis-12002.re-cluster2.ps-redislabs.org:12002" \
         "redis-12002.re-cluster3.ps-redislabs.org:12002")
def_weights=("1.0" "0.5" "0.25")

{
  echo "# Generated by configure.sh on $(date)"
  echo "db.count=$COUNT"
  echo
} > "$OUT"

for i in $(seq 1 "$COUNT"); do
  idx=$((i-1))
  echo
  echo "----- Database $i $( [ "$i" = "1" ] && echo '(PRIMARY)' ) -----"
  NAME=$(ask "  Name"            "${def_names[$idx]}")
  EP=$(ask   "  Endpoint host:port" "${def_eps[$idx]}")
  EP="${EP#redis://}"; EP="${EP#rediss://}"   # strip scheme if pasted
  WEIGHT=$(ask "  Weight (higher = preferred)" "${def_weights[$idx]}")

  AUTH=$(ask "  Auth type (none/password/acl)" "none")
  USER=""; PASS=""
  case "$AUTH" in
    password) PASS=$(ask "    Password" "") ;;
    acl)      USER=$(ask "    Username" ""); PASS=$(ask "    Password" "") ;;
    *)        : ;;  # none
  esac
  TLS=$(ask "  Use TLS? (true/false)" "false")

  {
    echo "db.$i.name=$NAME"
    echo "db.$i.endpoint=$EP"
    echo "db.$i.weight=$WEIGHT"
    echo "db.$i.username=$USER"
    echo "db.$i.password=$PASS"
    echo "db.$i.tls=$TLS"
    echo
  } >> "$OUT"
done

# Advanced tuning (threads, circuit-breaker thresholds, timeouts) uses built-in
# defaults - no need to set anything here. To override, copy the relevant keys
# from demo.properties.example into this file.
echo "# Advanced tuning is optional - see demo.properties.example for all keys." >> "$OUT"

echo
echo "Wrote $OUT:"
echo "------------------------------------------------------------"
grep -E '^db\.' "$OUT"
echo "------------------------------------------------------------"
echo "Start the demo with:  ./scripts/run.sh"
